// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI (migrate, studio, etc.) needs a direct connection.
    // The app runtime uses the driver adapter with the pooler URL instead.
    url: process.env["DIRECT_URL"] ?? "",
  },
});
