startPage = "Привет"
catalogPage = "Каталоги {0}"
threadItemPage = "Катушка\n{0}\nНомер: {1}\nВ наличии:\n{2} маленьких\n{3}Больших"
todoPage = "Список покупок\nНужно купить:\n{0}"

threadTextButton = "Нитки"
todoListButton = "Список покупок"
backToButton = "Вернуться назад"
plusOne = "+1"
minusOne = "-1"
plusOneBig = "+1 Бл."
minusOneBig = "-1 Бл."
